//https://dev.to/jacksbridger/how-to-setup-cloudflare-r2-bucket-generate-access-key-4icd
export const CLOUDFLARE_R2 = {
    CLOUDFLARE_R2_ACCOUNT_ID: process.env.CLOUDFLARE_R2_ACCOUNT_ID,
    CLOUDFLARE_R2_BUCKET_NAME: process.env.CLOUDFLARE_R2_BUCKET_NAME,
    CLOUDFLARE_R2_PUBLIC_ACCESS_KEY: process.env.CLOUDFLARE_R2_PUBLIC_ACCESS_KEY,
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY
}

export const AMAZON_S3 = {
    AMAZON_S2_BUCKET_NAME: process.env.AMAZON_S2_BUCKET_NAME,
    AMAZON_S2_BUCKET_REGION: process.env.AMAZON_S2_BUCKET_REGION,
    AMAZON_S2_PUBLIC_ACCESS_KEY: process.env.AMAZON_S2_PUBLIC_ACCESS_KEY,
    AMAZON_S2_SECRET_ACCESS_KEY: process.env.AMAZON_S2_SECRET_ACCESS_KEY
}